### ISSUE TITLE
Personal request

### ISSUE THREAD

**Issue by Cleboost** [Templater/usechannel#1]
Hello, sorry to bother you and write here but it was the only way for me to contact you. I saw that you have an organization called templater. I was wondering if it was still active/useful and if not if you could give me the url. Thank you for taking the time to read my message. Clément

**Comment by Mixerou** [comment]
Hi Clément,

Apologies for the delayed response. Thank you for reaching out and your interest in the `Templater` organization. Currently, the organization is reserved for future purposes and is not actively in use. So, I regret to inform you that I am unable to grant you access rights to the organization at this time.

Best regards,
Ivan
